[project]
name = "corsogiungla"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy==2.4.1",
    "pandas==3.0.0",
    "pandas-stubs~=3.0.0",
    "ruff>=0.14.14",
]
